### ISSUE TITLE
Inquiry Sequence Adapter

### ISSUE THREAD

**Issue by njausxl** [plant-plasticity/Evolutionary-flexibility-in-flooding-response-2019#1]
Dear Professor Reynosoma 

I have recently read your article，I downloaded the raw data of your Ribo-seq, TRAP-seq and would like to use your data for some other research work.

But I have a problem, what is the **Adapter** of your TRAP-seq data, can you tell me? For example **SRX5554400**.
Best wishes to you

Xiaoliang

note: "SRX5554400: GSM3682431: OS_TRA_CON1 [OS-TRACON1]; Oryza sativa Japonica Group; RNA-Seq
1 ILLUMINA (Illumina HiSeq 3000) run: 32.2M spots, 1.6G bases, 747.3Mb downloads"

**Comment by reynosoma** [comment]
Dear Xiaoliang,

We used the adapters from the protocol described here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4441129/. You can look at the supplemental table 1 for the sequences. 

Best,
Mauricio Reynoso

**Comment by njausxl** [comment]
> Dear Xiaoliang,
> 
> We used the adapters from the protocol described here: [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4441129 /](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4441129/). You can look at the supplemental table 1 for the sequences.
> 
> Best, Mauricio Reynoso

**Comment by njausxl** [comment]
Dear Professor Reynosoma

Your help is very important to my work！
Thank you very much! 
Best wishes to you,
Xiaoliang

**Comment by njausxl** [comment]
Dear Professor Reynosoma，

Thank you very much!
I'm very sorry to have to bother you again!

I followed your reminder, went to download and read the article, downloaded all the primer sequences from **table1**, and tried them all, but still could not remove the Adapter sequences from the row data cleanly, Only **30%** of the adapters in all sequences can be removed, obviously, there are still a lot of adapters that have not been removed.

I found “_tomato-root-atlas-2020/Scripts/Trimming_Kallist_STAR_mapping.sh_ ”in your lab article on GitHub（adapter： GATCGGAAGAGCACA）, and found the adapter sequence of **TRAP-seq** in it, but I found that it can only remove 32.4% of the adapter.
  _Total reads processed: 29,345,808
  Reads with adapters: 9,516,395 (32.4%)
  Reads written (passing filters): 29,345,808 (100.0%)_
This batch of TRAP-seq data:
- SRR8763815
- SRR8763816
- SRR8763817
- SRR8763818
- SRR8763819
- SRR8763820
- SRR8763821
- SRR8763822

I just started to learn bioinformatics data on my own, so I have a problem and can only ask an expert like you, is the primer of **TRAP-seq not universal,** and why it cannot be removed without specifying the adapter.

**Software like Trim_galore, fastp, and even fastqc do not detect its adapter,** I don't know what is the reason.
If you know, can you answer my confusion?

Thank you very much!
Best wishes to you,
Xiaoliang

**Comment by reynosoma** [comment]
Dear Xiaoliang,
The polyA mRNA from TRAP samples were prepared following this protocol: http://plant-plasticity.github.io/resources/Brads%20Rapid%20Ravi%20for%20low%20mRNA-share.pdf. The purification uses biotin-oligodT that contains a linker sequence. Reads with this sequence can be trimmed or excluded as well (this step will add to the ones you filtered).
Next, the libraries were prepared following http://plant-plasticity.github.io/resources/Brads%20Rapid%20Ravi%20for%20low%20mRNA-share.pdf. 
In these documents you can find the adapters to trim. 
Best,  Mauricio Reynoso

**Comment by njausxl** [comment]
Thank you very much!
Thank you for your rest time to answer my questions.



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/16/2022 21:52 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [plant-plasticity/Evolutionary-flexibility-in-flooding-response-2019] Inquiry Sequence Adapter (Issue #1) |

Dear Xiaoliang,
The polyA mRNA from TRAP samples were prepared following this protocol: http://plant-plasticity.github.io/resources/Brads%20Rapid%20Ravi%20for%20low%20mRNA-share.pdf. The purification uses biotin-oligodT that contains a linker sequence. Reads with this sequence can be trimmed or excluded as well (this step will add to the ones you filtered).
Next, the libraries were prepared following http://plant-plasticity.github.io/resources/Brads%20Rapid%20Ravi%20for%20low%20mRNA-share.pdf.
In these documents you can find the adapters to trim.
Best, Mauricio Reynoso
